import nodemailer from "nodemailer";

export const handler = async (event) => {
  if (event.httpMethod !== "POST") {
    return { statusCode: 405, body: "Method Not Allowed" };
  }

  try {
    const request = JSON.parse(event.body);
    const { name, email, subject, message } = request;

    const transporter = nodemailer.createTransport({
      host: "smtp.gmail.com",
      port: 587,
      secure: false, // true for 465, false for other ports
      auth: {
        user: "support.neuroscan.ai@gmail.com",
        pass: "lbgl hhgl apkf bdbg",
      },
    });

    const html_owner = `
      <html>
        <body style="font-family: Arial, sans-serif; background-color: #f1f5f9; padding: 20px;">
          <div style="max-width: 600px; margin: auto; padding: 30px; background-color: #ffffff; border-radius: 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); border-top: 5px solid #3b82f6;">
              <div style="text-align: center; margin-bottom: 20px;">
                  <img src="https://neuro-scan-ai.netlify.app/favicon.svg" alt="NeuroScan AI Logo" width="50" style="display: block; margin: 0 auto 10px auto;">
              </div>
              <h2 style="color: #1e293b; margin-top: 0; text-align: center;">New Contact Request</h2>
              <hr style="border: 0; border-top: 1px solid #e2e8f0; margin-bottom: 20px;">
              <p style="color: #475569;"><strong>From:</strong> ${name}</p>
              <p style="color: #475569;"><strong>Email:</strong> <a href="mailto:${email}" style="color: #3b82f6;">${email}</a></p>
              <p style="color: #475569;"><strong>Subject:</strong> ${subject}</p>
              <h3 style="color: #1e293b; margin-top: 30px;">Message:</h3>
              <div style="background-color: #f8fafc; padding: 20px; border-left: 4px solid #3b82f6; border-radius: 6px; color: #334155; white-space: pre-wrap; font-size: 15px;">${message}</div>
              <p style="font-size: 12px; color: #94a3b8; text-align: center; margin-top: 40px;">System generated by NeuroScan AI Backend</p>
          </div>
        </body>
      </html>
    `;

    const html_user = `
      <html>
        <body style="font-family: Arial, sans-serif; background-color: #f4f4f5; padding: 20px;">
          <div style="max-width: 600px; margin: auto; padding: 40px; background-color: #ffffff; border-radius: 16px; box-shadow: 0 10px 25px rgba(139, 92, 246, 0.1); border-top: 6px solid #8b5cf6;">
              <div style="text-align: center; margin-bottom: 30px;">
                  <img src="https://neuro-scan-ai.netlify.app/favicon.svg" alt="NeuroScan AI Brain Logo" width="60" style="display: block; margin: 0 auto 15px auto;">
                  <h1 style="color: #8b5cf6; margin: 0; font-size: 28px;">NeuroScan AI</h1>
                  <p style="color: #94a3b8; font-size: 14px; margin-top: 5px; text-transform: uppercase; letter-spacing: 1px;">Request Confirmation</p>
              </div>
              <p style="color: #334155; font-size: 17px;">Hi <strong>${name}</strong>,</p>
              <p style="color: #475569; font-size: 15px; line-height: 1.6;">Thank you for reaching out to us! We have successfully received your message regarding <strong>"${subject}"</strong>.</p>
              <p style="color: #475569; font-size: 15px; line-height: 1.6;">Our team will review your inquiry and get back to you to assist you shortly.</p>
              
              <div style="background-color: #f8fafc; padding: 20px; border-radius: 10px; margin: 30px 0;">
                  <p style="margin: 0; color: #64748b; font-size: 14px; font-style: italic;">Your Message:</p>
                  <p style="margin: 10px 0 0 0; color: #475569; white-space: pre-wrap; font-size: 15px;">"${message}"</p>
              </div>
              
              <p style="color: #334155; font-size: 15px; margin-top: 30px;">Best regards,<br><span style="font-weight: bold; color: #8b5cf6;">The NeuroScan AI Team</span></p>
              <hr style="border: 0; border-top: 1px solid #e2e8f0; margin-top: 40px;">
              <p style="font-size: 13px; color: #94a3b8; text-align: center;">Visit our <a href="https://neuro-scan-ai.netlify.app" style="color: #8b5cf6; text-decoration: none; font-weight: 500;">WebApp</a> • Check our <a href="https://github.com/Nrusimha-Sai/NeuroScan-AI" style="color: #8b5cf6; text-decoration: none; font-weight: 500;">GitHub</a></p>
          </div>
        </body>
      </html>
    `;

    // Mail to owner
    await transporter.sendMail({
      from: '"NeuroScan AI" <support.neuroscan.ai@gmail.com>',
      to: "support.neuroscan.ai@gmail.com",
      replyTo: email,
      subject: `New Inquiry: ${subject}`,
      html: html_owner,
    });

    // Mail to user
    await transporter.sendMail({
      from: '"NeuroScan AI" <support.neuroscan.ai@gmail.com>',
      to: email,
      subject: `Receipt: ${subject}`,
      html: html_user,
    });

    return {
      statusCode: 200,
      body: JSON.stringify({ success: true, message: "Email sent successfully" }),
    };
  } catch (error) {
    console.error("Error sending email:", error);
    return {
      statusCode: 500,
      body: JSON.stringify({ success: false, error: "Failed to send email" }),
    };
  }
};
